# Azure job template for the most common job in CI.

parameters:
  name: 'Default'  # Defaults for any parameters that aren't specified
  vmImage: 'Ubuntu-16.04'
  numpyCmd: 'pip install numpy'
  astropyCmd: 'pip install astropy'
  synphotCmd: 'pip install synphot'
  pythonVersion: '3.7'

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.pythonVersion }}
      architecture: 'x64'

  - script: |
      sudo apt-get install libxml2-utils
      python -m pip install --upgrade pip setuptools
      ${{ parameters.numpyCmd }}
      pip install scipy beautifulsoup4 pytest-astropy
      ${{ parameters.astropyCmd }}
      ${{ parameters.synphotCmd }}
      python setup.py test --open-files
    displayName: 'Run tests'
